/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelReference'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.Account = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.ModelReference);
  }
}(this, function(ApiClient, ModelReference) {
  'use strict';




  /**
   * The Account model module.
   * @module model/Account
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Account</code>.
   * @alias module:model/Account
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Account} obj Optional instance to populate.
   * @return {module:model/Account} The populated <code>Account</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('active')) {
        obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('number')) {
        obj['number'] = ApiClient.convertToType(data['number'], 'String');
      }
      if (data.hasOwnProperty('revision')) {
        obj['revision'] = ApiClient.convertToType(data['revision'], 'Number');
      }
      if (data.hasOwnProperty('cashJournalRelevant')) {
        obj['cashJournalRelevant'] = ApiClient.convertToType(data['cashJournalRelevant'], 'Boolean');
      }
      if (data.hasOwnProperty('denominationInput')) {
        obj['denominationInput'] = ApiClient.convertToType(data['denominationInput'], 'Boolean');
      }
      if (data.hasOwnProperty('exclusive')) {
        obj['exclusive'] = ApiClient.convertToType(data['exclusive'], 'Boolean');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('producer')) {
        obj['producer'] = ModelReference.constructFromObject(data['producer']);
      }
      if (data.hasOwnProperty('requiresSerialNumber')) {
        obj['requiresSerialNumber'] = ApiClient.convertToType(data['requiresSerialNumber'], 'Boolean');
      }
      if (data.hasOwnProperty('revenueAccount')) {
        obj['revenueAccount'] = ModelReference.constructFromObject(data['revenueAccount']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * indicates whether the object is active for use or not
   * @member {Boolean} active
   */
  exports.prototype['active'] = undefined;
  /**
   * global object uuid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * number of the object, like it is set in backoffice; will be removed when active=false
   * @member {String} number
   */
  exports.prototype['number'] = undefined;
  /**
   * the revision number of the object. revision numbers are unique per object-type. there is is no object of the same type with identical revision numbers.
   * @member {Number} revision
   */
  exports.prototype['revision'] = undefined;
  /**
   * @member {Boolean} cashJournalRelevant
   */
  exports.prototype['cashJournalRelevant'] = undefined;
  /**
   * @member {Boolean} denominationInput
   */
  exports.prototype['denominationInput'] = undefined;
  /**
   * @member {Boolean} exclusive
   */
  exports.prototype['exclusive'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/ModelReference} producer
   */
  exports.prototype['producer'] = undefined;
  /**
   * @member {Boolean} requiresSerialNumber
   */
  exports.prototype['requiresSerialNumber'] = undefined;
  /**
   * @member {module:model/ModelReference} revenueAccount
   */
  exports.prototype['revenueAccount'] = undefined;
  /**
   * @member {module:model/Account.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "DEPOSIT"
     * @const
     */
    "DEPOSIT": "DEPOSIT",
    /**
     * value: "WITHDRAWAL"
     * @const
     */
    "WITHDRAWAL": "WITHDRAWAL"  };


  return exports;
}));


