/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelReference', 'model/Rating', 'model/Weather'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelReference'), require('./Rating'), require('./Weather'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudApiV3JsClient) {
      root.CloudApiV3JsClient = {};
    }
    root.CloudApiV3JsClient.DayRating = factory(root.CloudApiV3JsClient.ApiClient, root.CloudApiV3JsClient.ModelReference, root.CloudApiV3JsClient.Rating, root.CloudApiV3JsClient.Weather);
  }
}(this, function(ApiClient, ModelReference, Rating, Weather) {
  'use strict';




  /**
   * The DayRating model module.
   * @module model/DayRating
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>DayRating</code>.
   * @alias module:model/DayRating
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>DayRating</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DayRating} obj Optional instance to populate.
   * @return {module:model/DayRating} The populated <code>DayRating</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cashier')) {
        obj['cashier'] = ModelReference.constructFromObject(data['cashier']);
      }
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('organizationalUnit')) {
        obj['organizationalUnit'] = ModelReference.constructFromObject(data['organizationalUnit']);
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = Rating.constructFromObject(data['rating']);
      }
      if (data.hasOwnProperty('receipts')) {
        obj['receipts'] = ApiClient.convertToType(data['receipts'], 'Number');
      }
      if (data.hasOwnProperty('revenue')) {
        obj['revenue'] = ApiClient.convertToType(data['revenue'], 'Number');
      }
      if (data.hasOwnProperty('visitors')) {
        obj['visitors'] = ApiClient.convertToType(data['visitors'], 'Number');
      }
      if (data.hasOwnProperty('weather')) {
        obj['weather'] = Weather.constructFromObject(data['weather']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ModelReference} cashier
   */
  exports.prototype['cashier'] = undefined;
  /**
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/ModelReference} organizationalUnit
   */
  exports.prototype['organizationalUnit'] = undefined;
  /**
   * @member {module:model/Rating} rating
   */
  exports.prototype['rating'] = undefined;
  /**
   * @member {Number} receipts
   */
  exports.prototype['receipts'] = undefined;
  /**
   * @member {Number} revenue
   */
  exports.prototype['revenue'] = undefined;
  /**
   * @member {Number} visitors
   */
  exports.prototype['visitors'] = undefined;
  /**
   * @member {module:model/Weather} weather
   */
  exports.prototype['weather'] = undefined;



  return exports;
}));


