/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3
 * Contact: support@combase.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.ForbiddenError = factory(root.KoronacloudApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ForbiddenError model module.
   * @module model/ForbiddenError
   * @version 3
   */

  /**
   * Constructs a new <code>ForbiddenError</code>.
   * @alias module:model/ForbiddenError
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ForbiddenError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ForbiddenError} obj Optional instance to populate.
   * @return {module:model/ForbiddenError} The populated <code>ForbiddenError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
    }
    return obj;
  }

  /**
   * a short description of the error in english
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * the code for client-side evaluation of the error
   * @member {module:model/ForbiddenError.CodeEnum} code
   */
  exports.prototype['code'] = undefined;


  /**
   * Allowed values for the <code>code</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CodeEnum = {
    /**
     * value: "CLOUD_ACCOUNT_DISABLED"
     * @const
     */
    "CLOUD_ACCOUNT_DISABLED": "CLOUD_ACCOUNT_DISABLED",
    /**
     * value: "POINT_OF_SALE_NOT_EXTERNAL"
     * @const
     */
    "POINT_OF_SALE_NOT_EXTERNAL": "POINT_OF_SALE_NOT_EXTERNAL",
    /**
     * value: "POINT_OF_SALE_NOT_COUPLED"
     * @const
     */
    "POINT_OF_SALE_NOT_COUPLED": "POINT_OF_SALE_NOT_COUPLED",
    /**
     * value: "POINT_OF_SALE_COUPLED_WITH_OTHER_DEVICE"
     * @const
     */
    "POINT_OF_SALE_COUPLED_WITH_OTHER_DEVICE": "POINT_OF_SALE_COUPLED_WITH_OTHER_DEVICE",
    /**
     * value: "DELETE_NOT_ALLOWED"
     * @const
     */
    "DELETE_NOT_ALLOWED": "DELETE_NOT_ALLOWED",
    /**
     * value: "SAVE_OR_UPDATE_NOT_ALLOWED"
     * @const
     */
    "SAVE_OR_UPDATE_NOT_ALLOWED": "SAVE_OR_UPDATE_NOT_ALLOWED",
    /**
     * value: "ADDITIONAL_CLOUD_PACKAGE_REQUIRED"
     * @const
     */
    "ADDITIONAL_CLOUD_PACKAGE_REQUIRED": "ADDITIONAL_CLOUD_PACKAGE_REQUIRED",
    /**
     * value: "ADDITIONAL_API_ACCESS_REQUIRED"
     * @const
     */
    "ADDITIONAL_API_ACCESS_REQUIRED": "ADDITIONAL_API_ACCESS_REQUIRED"  };


  return exports;
}));


