/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudApiV3JsClient) {
      root.CloudApiV3JsClient = {};
    }
    root.CloudApiV3JsClient.NotFoundError = factory(root.CloudApiV3JsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The NotFoundError model module.
   * @module model/NotFoundError
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>NotFoundError</code>.
   * @alias module:model/NotFoundError
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>NotFoundError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotFoundError} obj Optional instance to populate.
   * @return {module:model/NotFoundError} The populated <code>NotFoundError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
    }
    return obj;
  }

  /**
   * a short description of the error in english
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * the code for client-side evaluation of the error
   * @member {module:model/NotFoundError.CodeEnum} code
   */
  exports.prototype['code'] = undefined;


  /**
   * Allowed values for the <code>code</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CodeEnum = {
    /**
     * value: "ACCOUNT_NOT_FOUND"
     * @const
     */
    "ACCOUNT_NOT_FOUND": "ACCOUNT_NOT_FOUND",
    /**
     * value: "MODEL_ID_NOT_FOUND"
     * @const
     */
    "MODEL_ID_NOT_FOUND": "MODEL_ID_NOT_FOUND",
    /**
     * value: "NUMBER_NOT_FOUND"
     * @const
     */
    "NUMBER_NOT_FOUND": "NUMBER_NOT_FOUND",
    /**
     * value: "DATE_NOT_FOUND"
     * @const
     */
    "DATE_NOT_FOUND": "DATE_NOT_FOUND",
    /**
     * value: "INDEX_NOT_FOUND"
     * @const
     */
    "INDEX_NOT_FOUND": "INDEX_NOT_FOUND",
    /**
     * value: "CONDITION_MISMATCH"
     * @const
     */
    "CONDITION_MISMATCH": "CONDITION_MISMATCH"  };


  return exports;
}));


