/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3
 * Contact: support@combase.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TopSeller'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TopSeller'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.PeriodListTopSeller = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.TopSeller);
  }
}(this, function(ApiClient, TopSeller) {
  'use strict';




  /**
   * The PeriodListTopSeller model module.
   * @module model/PeriodListTopSeller
   * @version 3
   */

  /**
   * Constructs a new <code>PeriodListTopSeller</code>.
   * @alias module:model/PeriodListTopSeller
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PeriodListTopSeller</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PeriodListTopSeller} obj Optional instance to populate.
   * @return {module:model/PeriodListTopSeller} The populated <code>PeriodListTopSeller</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Date');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Date');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [TopSeller]);
      }
    }
    return obj;
  }

  /**
   * @member {Date} start
   */
  exports.prototype['start'] = undefined;
  /**
   * @member {Date} end
   */
  exports.prototype['end'] = undefined;
  /**
   * @member {Array.<module:model/TopSeller>} results
   */
  exports.prototype['results'] = undefined;



  return exports;
}));


