/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AddressInformation', 'model/CompanyIdentification'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AddressInformation'), require('./CompanyIdentification'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudApiV3JsClient) {
      root.CloudApiV3JsClient = {};
    }
    root.CloudApiV3JsClient.ProductTransferInvolvedPartyInformationData = factory(root.CloudApiV3JsClient.ApiClient, root.CloudApiV3JsClient.AddressInformation, root.CloudApiV3JsClient.CompanyIdentification);
  }
}(this, function(ApiClient, AddressInformation, CompanyIdentification) {
  'use strict';




  /**
   * The ProductTransferInvolvedPartyInformationData model module.
   * @module model/ProductTransferInvolvedPartyInformationData
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>ProductTransferInvolvedPartyInformationData</code>.
   * @alias module:model/ProductTransferInvolvedPartyInformationData
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ProductTransferInvolvedPartyInformationData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductTransferInvolvedPartyInformationData} obj Optional instance to populate.
   * @return {module:model/ProductTransferInvolvedPartyInformationData} The populated <code>ProductTransferInvolvedPartyInformationData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('address')) {
        obj['address'] = AddressInformation.constructFromObject(data['address']);
      }
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('identification')) {
        obj['identification'] = CompanyIdentification.constructFromObject(data['identification']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AddressInformation} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {module:model/CompanyIdentification} identification
   */
  exports.prototype['identification'] = undefined;



  return exports;
}));


