/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.Rating = factory(root.KoronacloudApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Rating model module.
   * @module model/Rating
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Rating</code>.
   * @alias module:model/Rating
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Rating</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Rating} obj Optional instance to populate.
   * @return {module:model/Rating} The populated <code>Rating</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('assortment')) {
        obj['assortment'] = ApiClient.convertToType(data['assortment'], 'Number');
      }
      if (data.hasOwnProperty('customers')) {
        obj['customers'] = ApiClient.convertToType(data['customers'], 'Number');
      }
      if (data.hasOwnProperty('employees')) {
        obj['employees'] = ApiClient.convertToType(data['employees'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} assortment
   */
  exports.prototype['assortment'] = undefined;
  /**
   * @member {Number} customers
   */
  exports.prototype['customers'] = undefined;
  /**
   * @member {Number} employees
   */
  exports.prototype['employees'] = undefined;



  return exports;
}));


