/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelReference', 'model/PeriodListTopSeller'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelReference'), require('./PeriodListTopSeller'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.StatisticListTopSeller = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.ModelReference, root.KoronacloudApiV3.PeriodListTopSeller);
  }
}(this, function(ApiClient, ModelReference, PeriodListTopSeller) {
  'use strict';




  /**
   * The StatisticListTopSeller model module.
   * @module model/StatisticListTopSeller
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>StatisticListTopSeller</code>.
   * @alias module:model/StatisticListTopSeller
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>StatisticListTopSeller</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatisticListTopSeller} obj Optional instance to populate.
   * @return {module:model/StatisticListTopSeller} The populated <code>StatisticListTopSeller</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('organizationalUnit')) {
        obj['organizationalUnit'] = ModelReference.constructFromObject(data['organizationalUnit']);
      }
      if (data.hasOwnProperty('currentPeriod')) {
        obj['currentPeriod'] = PeriodListTopSeller.constructFromObject(data['currentPeriod']);
      }
      if (data.hasOwnProperty('previousPeriod')) {
        obj['previousPeriod'] = PeriodListTopSeller.constructFromObject(data['previousPeriod']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ModelReference} organizationalUnit
   */
  exports.prototype['organizationalUnit'] = undefined;
  /**
   * @member {module:model/PeriodListTopSeller} currentPeriod
   */
  exports.prototype['currentPeriod'] = undefined;
  /**
   * @member {module:model/PeriodListTopSeller} previousPeriod
   */
  exports.prototype['previousPeriod'] = undefined;



  return exports;
}));


