/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelReference', 'model/StockReceiptItemAmount', 'model/StockReceiptItemIdentification', 'model/StockReceiptItemPurchasePrice'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelReference'), require('./StockReceiptItemAmount'), require('./StockReceiptItemIdentification'), require('./StockReceiptItemPurchasePrice'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.StockReceiptItem = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.ModelReference, root.KoronacloudApiV3.StockReceiptItemAmount, root.KoronacloudApiV3.StockReceiptItemIdentification, root.KoronacloudApiV3.StockReceiptItemPurchasePrice);
  }
}(this, function(ApiClient, ModelReference, StockReceiptItemAmount, StockReceiptItemIdentification, StockReceiptItemPurchasePrice) {
  'use strict';




  /**
   * The StockReceiptItem model module.
   * @module model/StockReceiptItem
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>StockReceiptItem</code>.
   * @alias module:model/StockReceiptItem
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>StockReceiptItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StockReceiptItem} obj Optional instance to populate.
   * @return {module:model/StockReceiptItem} The populated <code>StockReceiptItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = StockReceiptItemAmount.constructFromObject(data['amount']);
      }
      if (data.hasOwnProperty('identification')) {
        obj['identification'] = StockReceiptItemIdentification.constructFromObject(data['identification']);
      }
      if (data.hasOwnProperty('index')) {
        obj['index'] = ApiClient.convertToType(data['index'], 'Number');
      }
      if (data.hasOwnProperty('product')) {
        obj['product'] = ModelReference.constructFromObject(data['product']);
      }
      if (data.hasOwnProperty('purchasePrice')) {
        obj['purchasePrice'] = StockReceiptItemPurchasePrice.constructFromObject(data['purchasePrice']);
      }
      if (data.hasOwnProperty('revision')) {
        obj['revision'] = ApiClient.convertToType(data['revision'], 'Number');
      }
      if (data.hasOwnProperty('shelfLife')) {
        obj['shelfLife'] = ApiClient.convertToType(data['shelfLife'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/StockReceiptItemAmount} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {module:model/StockReceiptItemIdentification} identification
   */
  exports.prototype['identification'] = undefined;
  /**
   * @member {Number} index
   */
  exports.prototype['index'] = undefined;
  /**
   * @member {module:model/ModelReference} product
   */
  exports.prototype['product'] = undefined;
  /**
   * @member {module:model/StockReceiptItemPurchasePrice} purchasePrice
   */
  exports.prototype['purchasePrice'] = undefined;
  /**
   * @member {Number} revision
   */
  exports.prototype['revision'] = undefined;
  /**
   * @member {Date} shelfLife
   */
  exports.prototype['shelfLife'] = undefined;



  return exports;
}));


