/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DayTimePeriod', 'model/TotalPeriod'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DayTimePeriod'), require('./TotalPeriod'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.Validity = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.DayTimePeriod, root.KoronacloudApiV3.TotalPeriod);
  }
}(this, function(ApiClient, DayTimePeriod, TotalPeriod) {
  'use strict';




  /**
   * The Validity model module.
   * @module model/Validity
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Validity</code>.
   * @alias module:model/Validity
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Validity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Validity} obj Optional instance to populate.
   * @return {module:model/Validity} The populated <code>Validity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('daily')) {
        obj['daily'] = DayTimePeriod.constructFromObject(data['daily']);
      }
      if (data.hasOwnProperty('daysOfMonth')) {
        obj['daysOfMonth'] = ApiClient.convertToType(data['daysOfMonth'], ['Number']);
      }
      if (data.hasOwnProperty('daysOfWeek')) {
        obj['daysOfWeek'] = ApiClient.convertToType(data['daysOfWeek'], ['String']);
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = TotalPeriod.constructFromObject(data['total']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DayTimePeriod} daily
   */
  exports.prototype['daily'] = undefined;
  /**
   * @member {Array.<Number>} daysOfMonth
   */
  exports.prototype['daysOfMonth'] = undefined;
  /**
   * @member {Array.<module:model/Validity.DaysOfWeekEnum>} daysOfWeek
   */
  exports.prototype['daysOfWeek'] = undefined;
  /**
   * @member {module:model/TotalPeriod} total
   */
  exports.prototype['total'] = undefined;


  /**
   * Allowed values for the <code>daysOfWeek</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DaysOfWeekEnum = {
    /**
     * value: "MONDAY"
     * @const
     */
    "MONDAY": "MONDAY",
    /**
     * value: "TUESDAY"
     * @const
     */
    "TUESDAY": "TUESDAY",
    /**
     * value: "WEDNESDAY"
     * @const
     */
    "WEDNESDAY": "WEDNESDAY",
    /**
     * value: "THURSDAY"
     * @const
     */
    "THURSDAY": "THURSDAY",
    /**
     * value: "FRIDAY"
     * @const
     */
    "FRIDAY": "FRIDAY",
    /**
     * value: "SATURDAY"
     * @const
     */
    "SATURDAY": "SATURDAY",
    /**
     * value: "SUNDAY"
     * @const
     */
    "SUNDAY": "SUNDAY"  };


  return exports;
}));


