/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AddOrUpdateResult', 'model/BadRequestError', 'model/ForbiddenError', 'model/Inventory', 'model/InventoryList', 'model/InventoryListItem', 'model/MethodNotAllowedError', 'model/NotFoundError', 'model/ResultListInventory', 'model/ResultListInventoryList', 'model/ResultListInventoryListItem', 'model/TooManyRequestsError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AddOrUpdateResult'), require('../model/BadRequestError'), require('../model/ForbiddenError'), require('../model/Inventory'), require('../model/InventoryList'), require('../model/InventoryListItem'), require('../model/MethodNotAllowedError'), require('../model/NotFoundError'), require('../model/ResultListInventory'), require('../model/ResultListInventoryList'), require('../model/ResultListInventoryListItem'), require('../model/TooManyRequestsError'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.InventoriesApi = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.AddOrUpdateResult, root.KoronacloudApiV3.BadRequestError, root.KoronacloudApiV3.ForbiddenError, root.KoronacloudApiV3.Inventory, root.KoronacloudApiV3.InventoryList, root.KoronacloudApiV3.InventoryListItem, root.KoronacloudApiV3.MethodNotAllowedError, root.KoronacloudApiV3.NotFoundError, root.KoronacloudApiV3.ResultListInventory, root.KoronacloudApiV3.ResultListInventoryList, root.KoronacloudApiV3.ResultListInventoryListItem, root.KoronacloudApiV3.TooManyRequestsError);
  }
}(this, function(ApiClient, AddOrUpdateResult, BadRequestError, ForbiddenError, Inventory, InventoryList, InventoryListItem, MethodNotAllowedError, NotFoundError, ResultListInventory, ResultListInventoryList, ResultListInventoryListItem, TooManyRequestsError) {
  'use strict';

  /**
   * Inventories service.
   * @module api/InventoriesApi
   * @version 3.0.0
   */

  /**
   * Constructs a new InventoriesApi. 
   * @alias module:api/InventoriesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addInventories operation.
     * @callback module:api/InventoriesApi~addInventoriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AddOrUpdateResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * adds a batch of new inventories
     * 
     * @param {Array.<module:model/Inventory>} body a array of new inventories
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~addInventoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AddOrUpdateResult>}
     */
    this.addInventories = function(body, koronaAccountId, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addInventories");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling addInventories");
      }


      var pathParams = {
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AddOrUpdateResult];

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addInventoryInventoryListItems operation.
     * @callback module:api/InventoriesApi~addInventoryInventoryListItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AddOrUpdateResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * adds inventory list items
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {Array.<module:model/InventoryListItem>} body data to update
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~addInventoryInventoryListItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AddOrUpdateResult>}
     */
    this.addInventoryInventoryListItems = function(inventoryId, inventoryListId, body, koronaAccountId, callback) {
      var postBody = body;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling addInventoryInventoryListItems");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling addInventoryInventoryListItems");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addInventoryInventoryListItems");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling addInventoryInventoryListItems");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AddOrUpdateResult];

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}/items', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteInventory operation.
     * @callback module:api/InventoriesApi~deleteInventoryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deletes the single inventory (only allowed if hasBookedReceipts&#x3D;false)
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~deleteInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteInventory = function(inventoryId, koronaAccountId, callback) {
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling deleteInventory");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling deleteInventory");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteInventoryInventoryListItem operation.
     * @callback module:api/InventoriesApi~deleteInventoryInventoryListItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deletes the single inventory list item
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {String} productId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~deleteInventoryInventoryListItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteInventoryInventoryListItem = function(inventoryId, inventoryListId, productId, koronaAccountId, callback) {
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling deleteInventoryInventoryListItem");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling deleteInventoryInventoryListItem");
      }

      // verify the required parameter 'productId' is set
      if (productId === undefined || productId === null) {
        throw new Error("Missing the required parameter 'productId' when calling deleteInventoryInventoryListItem");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling deleteInventoryInventoryListItem");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'productId': productId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}/items/{productId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventories operation.
     * @callback module:api/InventoriesApi~getInventoriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResultListInventory} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists all inventories
     * 
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page number of the page to fetch
     * @param {Number} opts.size amount of objects to return per page
     * @param {String} opts.sort attribute to sort by (multiple separated by comma; max. 5)
     * @param {Number} opts.revision last revision number, objects with a greater revision than this will be returned
     * @param {Boolean} opts.includeDeleted indicates deleted objects should be loaded or not (default: false)
     * @param {module:api/InventoriesApi~getInventoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResultListInventory}
     */
    this.getInventories = function(koronaAccountId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling getInventories");
      }


      var pathParams = {
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort'],
        'revision': opts['revision'],
        'includeDeleted': opts['includeDeleted'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ResultListInventory;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventory operation.
     * @callback module:api/InventoriesApi~getInventoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Inventory} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns the single inventory
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~getInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Inventory}
     */
    this.getInventory = function(inventoryId, koronaAccountId, callback) {
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling getInventory");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling getInventory");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Inventory;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventoryInventoryList operation.
     * @callback module:api/InventoriesApi~getInventoryInventoryListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns the single inventory list
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~getInventoryInventoryListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryList}
     */
    this.getInventoryInventoryList = function(inventoryId, inventoryListId, koronaAccountId, callback) {
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling getInventoryInventoryList");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling getInventoryInventoryList");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling getInventoryInventoryList");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InventoryList;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventoryInventoryListItem operation.
     * @callback module:api/InventoriesApi~getInventoryInventoryListItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryListItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns the single inventory list item
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {String} productId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~getInventoryInventoryListItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryListItem}
     */
    this.getInventoryInventoryListItem = function(inventoryId, inventoryListId, productId, koronaAccountId, callback) {
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling getInventoryInventoryListItem");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling getInventoryInventoryListItem");
      }

      // verify the required parameter 'productId' is set
      if (productId === undefined || productId === null) {
        throw new Error("Missing the required parameter 'productId' when calling getInventoryInventoryListItem");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling getInventoryInventoryListItem");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'productId': productId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InventoryListItem;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}/items/{productId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventoryInventoryListItems operation.
     * @callback module:api/InventoriesApi~getInventoryInventoryListItemsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResultListInventoryListItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists all inventory list items
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page number of the page to fetch
     * @param {Number} opts.size amount of objects to return per page
     * @param {String} opts.sort attribute to sort by (multiple separated by comma; max. 5)
     * @param {Number} opts.revision last revision number, objects with a greater revision than this will be returned
     * @param {module:api/InventoriesApi~getInventoryInventoryListItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResultListInventoryListItem}
     */
    this.getInventoryInventoryListItems = function(inventoryId, inventoryListId, koronaAccountId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling getInventoryInventoryListItems");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling getInventoryInventoryListItems");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling getInventoryInventoryListItems");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort'],
        'revision': opts['revision'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ResultListInventoryListItem;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}/items', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventoryInventoryLists operation.
     * @callback module:api/InventoriesApi~getInventoryInventoryListsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResultListInventoryList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists all inventory lists
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page number of the page to fetch
     * @param {Number} opts.size amount of objects to return per page
     * @param {String} opts.sort attribute to sort by (multiple separated by comma; max. 5)
     * @param {Number} opts.revision last revision number, objects with a greater revision than this will be returned
     * @param {Boolean} opts.includeDeleted indicates deleted objects should be loaded or not (default: false)
     * @param {Date} opts.minCreateTime min (inclusive) create time of the receipt (ISO 8601; date, time and timezone)
     * @param {Date} opts.maxCreateTime max (inclusive) create time of the receipt (ISO 8601; date, time and timezone)
     * @param {Date} opts.minBookingTime min (inclusive) booking time of the receipt (ISO 8601; date, time and timezone)
     * @param {Date} opts.maxBookingTime max (inclusive) booking time of the receipt (ISO 8601; date, time and timezone)
     * @param {module:model/String} opts.bookingStatus booking status (possible values: BOOKED, IN_PROGRESS)
     * @param {module:api/InventoriesApi~getInventoryInventoryListsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResultListInventoryList}
     */
    this.getInventoryInventoryLists = function(inventoryId, koronaAccountId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling getInventoryInventoryLists");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling getInventoryInventoryLists");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort'],
        'revision': opts['revision'],
        'includeDeleted': opts['includeDeleted'],
        'minCreateTime': opts['minCreateTime'],
        'maxCreateTime': opts['maxCreateTime'],
        'minBookingTime': opts['minBookingTime'],
        'maxBookingTime': opts['maxBookingTime'],
        'bookingStatus': opts['bookingStatus'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ResultListInventoryList;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateInventory operation.
     * @callback module:api/InventoriesApi~updateInventoryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates the single inventory
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {module:model/Inventory} body the properties to update of the inventory
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~updateInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateInventory = function(inventoryId, body, koronaAccountId, callback) {
      var postBody = body;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling updateInventory");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateInventory");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling updateInventory");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateInventoryInventoryList operation.
     * @callback module:api/InventoriesApi~updateInventoryInventoryListCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates the single inventory list
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {module:model/InventoryList} body data to update
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~updateInventoryInventoryListCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateInventoryInventoryList = function(inventoryId, inventoryListId, body, koronaAccountId, callback) {
      var postBody = body;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling updateInventoryInventoryList");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling updateInventoryInventoryList");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateInventoryInventoryList");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling updateInventoryInventoryList");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateInventoryInventoryListItem operation.
     * @callback module:api/InventoriesApi~updateInventoryInventoryListItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates the single inventory list item
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {String} productId id of the related object (important: id should match the uuid-format)
     * @param {module:model/InventoryListItem} body data to update
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~updateInventoryInventoryListItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateInventoryInventoryListItem = function(inventoryId, inventoryListId, productId, body, koronaAccountId, callback) {
      var postBody = body;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling updateInventoryInventoryListItem");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling updateInventoryInventoryListItem");
      }

      // verify the required parameter 'productId' is set
      if (productId === undefined || productId === null) {
        throw new Error("Missing the required parameter 'productId' when calling updateInventoryInventoryListItem");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateInventoryInventoryListItem");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling updateInventoryInventoryListItem");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'productId': productId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}/items/{productId}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateInventoryInventoryListItems operation.
     * @callback module:api/InventoriesApi~updateInventoryInventoryListItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AddOrUpdateResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates inventory list items (property [product] required))
     * 
     * @param {String} inventoryId id of the related object (important: id should match the uuid-format)
     * @param {String} inventoryListId id of the related object (important: id should match the uuid-format)
     * @param {Array.<module:model/InventoryListItem>} body a array of inventory list items to update
     * @param {String} koronaAccountId account id of the korona.cloud account
     * @param {module:api/InventoriesApi~updateInventoryInventoryListItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AddOrUpdateResult>}
     */
    this.updateInventoryInventoryListItems = function(inventoryId, inventoryListId, body, koronaAccountId, callback) {
      var postBody = body;

      // verify the required parameter 'inventoryId' is set
      if (inventoryId === undefined || inventoryId === null) {
        throw new Error("Missing the required parameter 'inventoryId' when calling updateInventoryInventoryListItems");
      }

      // verify the required parameter 'inventoryListId' is set
      if (inventoryListId === undefined || inventoryListId === null) {
        throw new Error("Missing the required parameter 'inventoryListId' when calling updateInventoryInventoryListItems");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateInventoryInventoryListItems");
      }

      // verify the required parameter 'koronaAccountId' is set
      if (koronaAccountId === undefined || koronaAccountId === null) {
        throw new Error("Missing the required parameter 'koronaAccountId' when calling updateInventoryInventoryListItems");
      }


      var pathParams = {
        'inventoryId': inventoryId,
        'inventoryListId': inventoryListId,
        'koronaAccountId': koronaAccountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AddOrUpdateResult];

      return this.apiClient.callApi(
        '/accounts/{koronaAccountId}/inventories/{inventoryId}/inventoryLists/{inventoryListId}/items', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
