/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3
 * Contact: support@combase.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AddOrUpdateResult', 'model/BadRequestError', 'model/ForbiddenError', 'model/MethodNotAllowedError', 'model/NotFoundError', 'model/ResultListStockReceipt', 'model/ResultListStockReceiptItem', 'model/StockReceipt', 'model/StockReceiptItem', 'model/TooManyRequestsError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AddOrUpdateResult'), require('../model/BadRequestError'), require('../model/ForbiddenError'), require('../model/MethodNotAllowedError'), require('../model/NotFoundError'), require('../model/ResultListStockReceipt'), require('../model/ResultListStockReceiptItem'), require('../model/StockReceipt'), require('../model/StockReceiptItem'), require('../model/TooManyRequestsError'));
  } else {
    // Browser globals (root is window)
    if (!root.KoronacloudApiV3) {
      root.KoronacloudApiV3 = {};
    }
    root.KoronacloudApiV3.StockReceiptsKORONARetailApi = factory(root.KoronacloudApiV3.ApiClient, root.KoronacloudApiV3.AddOrUpdateResult, root.KoronacloudApiV3.BadRequestError, root.KoronacloudApiV3.ForbiddenError, root.KoronacloudApiV3.MethodNotAllowedError, root.KoronacloudApiV3.NotFoundError, root.KoronacloudApiV3.ResultListStockReceipt, root.KoronacloudApiV3.ResultListStockReceiptItem, root.KoronacloudApiV3.StockReceipt, root.KoronacloudApiV3.StockReceiptItem, root.KoronacloudApiV3.TooManyRequestsError);
  }
}(this, function(ApiClient, AddOrUpdateResult, BadRequestError, ForbiddenError, MethodNotAllowedError, NotFoundError, ResultListStockReceipt, ResultListStockReceiptItem, StockReceipt, StockReceiptItem, TooManyRequestsError) {
  'use strict';

  /**
   * StockReceiptsKORONARetail service.
   * @module api/StockReceiptsKORONARetailApi
   * @version 3
   */

  /**
   * Constructs a new StockReceiptsKORONARetailApi. 
   * @alias module:api/StockReceiptsKORONARetailApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addStockReceiptItems operation.
     * @callback module:api/StockReceiptsKORONARetailApi~addStockReceiptItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AddOrUpdateResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * adds stock-receipt items
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {Array.<module:model/StockReceiptItem>} body data to add
     * @param {module:api/StockReceiptsKORONARetailApi~addStockReceiptItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AddOrUpdateResult>}
     */
    this.addStockReceiptItems = function(accountId, stockReceiptIdOrNumber, body, callback) {
      var postBody = body;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling addStockReceiptItems");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling addStockReceiptItems");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addStockReceiptItems");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AddOrUpdateResult];

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}/items', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addStockReceipts operation.
     * @callback module:api/StockReceiptsKORONARetailApi~addStockReceiptsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AddOrUpdateResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * adds stock-receipts
     * 
     * @param {String} accountId the account id
     * @param {Array.<module:model/StockReceipt>} body data to add
     * @param {module:api/StockReceiptsKORONARetailApi~addStockReceiptsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AddOrUpdateResult>}
     */
    this.addStockReceipts = function(accountId, body, callback) {
      var postBody = body;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling addStockReceipts");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addStockReceipts");
      }


      var pathParams = {
        'accountId': accountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AddOrUpdateResult];

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteStockReceiptItem operation.
     * @callback module:api/StockReceiptsKORONARetailApi~deleteStockReceiptItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deletes the stock-receipt item
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {String} productIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {module:api/StockReceiptsKORONARetailApi~deleteStockReceiptItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteStockReceiptItem = function(accountId, stockReceiptIdOrNumber, productIdOrNumber, callback) {
      var postBody = null;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling deleteStockReceiptItem");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling deleteStockReceiptItem");
      }

      // verify the required parameter 'productIdOrNumber' is set
      if (productIdOrNumber === undefined || productIdOrNumber === null) {
        throw new Error("Missing the required parameter 'productIdOrNumber' when calling deleteStockReceiptItem");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber,
        'productIdOrNumber': productIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}/items/{productIdOrNumber}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getStockReceipt operation.
     * @callback module:api/StockReceiptsKORONARetailApi~getStockReceiptCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StockReceipt} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists the stock-receipt
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {module:api/StockReceiptsKORONARetailApi~getStockReceiptCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StockReceipt}
     */
    this.getStockReceipt = function(accountId, stockReceiptIdOrNumber, callback) {
      var postBody = null;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling getStockReceipt");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling getStockReceipt");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = StockReceipt;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getStockReceiptItem operation.
     * @callback module:api/StockReceiptsKORONARetailApi~getStockReceiptItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StockReceiptItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists the stock-receipt item
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {String} productIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {module:api/StockReceiptsKORONARetailApi~getStockReceiptItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StockReceiptItem}
     */
    this.getStockReceiptItem = function(accountId, stockReceiptIdOrNumber, productIdOrNumber, callback) {
      var postBody = null;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling getStockReceiptItem");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling getStockReceiptItem");
      }

      // verify the required parameter 'productIdOrNumber' is set
      if (productIdOrNumber === undefined || productIdOrNumber === null) {
        throw new Error("Missing the required parameter 'productIdOrNumber' when calling getStockReceiptItem");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber,
        'productIdOrNumber': productIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = StockReceiptItem;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}/items/{productIdOrNumber}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getStockReceiptItems operation.
     * @callback module:api/StockReceiptsKORONARetailApi~getStockReceiptItemsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResultListStockReceiptItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists all stock-receipt items
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page number of the page to fetch
     * @param {Number} opts.size amount of objects to return per page
     * @param {String} opts.sort attribute to sort by (multiple separated by comma; max. 5)
     * @param {Number} opts.revision last revision number, objects with a greater revision than this will be returned
     * @param {module:api/StockReceiptsKORONARetailApi~getStockReceiptItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResultListStockReceiptItem}
     */
    this.getStockReceiptItems = function(accountId, stockReceiptIdOrNumber, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling getStockReceiptItems");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling getStockReceiptItems");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort'],
        'revision': opts['revision'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ResultListStockReceiptItem;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}/items', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getStockReceipts operation.
     * @callback module:api/StockReceiptsKORONARetailApi~getStockReceiptsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResultListStockReceipt} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists all stock-receipts
     * 
     * @param {String} accountId the account id
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page number of the page to fetch
     * @param {Number} opts.size amount of objects to return per page
     * @param {String} opts.sort attribute to sort by (multiple separated by comma; max. 5)
     * @param {Number} opts.revision last revision number, objects with a greater revision than this will be returned
     * @param {Boolean} opts.includeDeleted indicates deleted objects should be loaded or not (default: false)
     * @param {Date} opts.minCreateTime min (inclusive) create time of the receipt (ISO 8601; date, time and timezone)
     * @param {Date} opts.maxCreateTime max (inclusive) create time of the receipt (ISO 8601; date, time and timezone)
     * @param {String} opts.organizationalUnit organizational unit
     * @param {String} opts.sourceOrganizationalUnit source organizational unit
     * @param {module:model/String} opts.bookingStatus booking status (possible values: BOOKED, IN_PROGRESS)
     * @param {module:api/StockReceiptsKORONARetailApi~getStockReceiptsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResultListStockReceipt}
     */
    this.getStockReceipts = function(accountId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling getStockReceipts");
      }


      var pathParams = {
        'accountId': accountId
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort'],
        'revision': opts['revision'],
        'includeDeleted': opts['includeDeleted'],
        'minCreateTime': opts['minCreateTime'],
        'maxCreateTime': opts['maxCreateTime'],
        'organizationalUnit': opts['organizationalUnit'],
        'sourceOrganizationalUnit': opts['sourceOrganizationalUnit'],
        'bookingStatus': opts['bookingStatus'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ResultListStockReceipt;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateStockReceipt operation.
     * @callback module:api/StockReceiptsKORONARetailApi~updateStockReceiptCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates the stock-receipt
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {module:model/StockReceipt} body data to update
     * @param {module:api/StockReceiptsKORONARetailApi~updateStockReceiptCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateStockReceipt = function(accountId, stockReceiptIdOrNumber, body, callback) {
      var postBody = body;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling updateStockReceipt");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling updateStockReceipt");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateStockReceipt");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateStockReceiptItem operation.
     * @callback module:api/StockReceiptsKORONARetailApi~updateStockReceiptItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates the stock-receipt item
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {String} productIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {module:model/StockReceiptItem} body data to update
     * @param {module:api/StockReceiptsKORONARetailApi~updateStockReceiptItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateStockReceiptItem = function(accountId, stockReceiptIdOrNumber, productIdOrNumber, body, callback) {
      var postBody = body;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling updateStockReceiptItem");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling updateStockReceiptItem");
      }

      // verify the required parameter 'productIdOrNumber' is set
      if (productIdOrNumber === undefined || productIdOrNumber === null) {
        throw new Error("Missing the required parameter 'productIdOrNumber' when calling updateStockReceiptItem");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateStockReceiptItem");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber,
        'productIdOrNumber': productIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}/items/{productIdOrNumber}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateStockReceiptItems operation.
     * @callback module:api/StockReceiptsKORONARetailApi~updateStockReceiptItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AddOrUpdateResult>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates stock-receipt items
     * 
     * @param {String} accountId the account id
     * @param {String} stockReceiptIdOrNumber id or number of the related object (important: if a number should match the uuid-format, the system will lookup for an id instead of a number)
     * @param {Array.<module:model/StockReceiptItem>} body data to update
     * @param {module:api/StockReceiptsKORONARetailApi~updateStockReceiptItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AddOrUpdateResult>}
     */
    this.updateStockReceiptItems = function(accountId, stockReceiptIdOrNumber, body, callback) {
      var postBody = body;

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling updateStockReceiptItems");
      }

      // verify the required parameter 'stockReceiptIdOrNumber' is set
      if (stockReceiptIdOrNumber === undefined || stockReceiptIdOrNumber === null) {
        throw new Error("Missing the required parameter 'stockReceiptIdOrNumber' when calling updateStockReceiptItems");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateStockReceiptItems");
      }


      var pathParams = {
        'accountId': accountId,
        'stockReceiptIdOrNumber': stockReceiptIdOrNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AddOrUpdateResult];

      return this.apiClient.callApi(
        '/accounts/{accountId}/stockReceipts/{stockReceiptIdOrNumber}/items', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
