/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KoronacloudApiV3);
  }
}(this, function(expect, KoronacloudApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KoronacloudApiV3.CustomerOrder();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomerOrder', function() {
    it('should create an instance of CustomerOrder', function() {
      // uncomment below and update the code to test CustomerOrder
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be.a(KoronacloudApiV3.CustomerOrder);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property revision (base name: "revision")', function() {
      // uncomment below and update the code to test the property revision
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property bookingTime (base name: "bookingTime")', function() {
      // uncomment below and update the code to test the property bookingTime
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property cashier (base name: "cashier")', function() {
      // uncomment below and update the code to test the property cashier
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property customerData (base name: "customerData")', function() {
      // uncomment below and update the code to test the property customerData
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property deposit (base name: "deposit")', function() {
      // uncomment below and update the code to test the property deposit
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property depositAccount (base name: "depositAccount")', function() {
      // uncomment below and update the code to test the property depositAccount
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property finishTime (base name: "finishTime")', function() {
      // uncomment below and update the code to test the property finishTime
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property organizationalUnit (base name: "organizationalUnit")', function() {
      // uncomment below and update the code to test the property organizationalUnit
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property pickUpTime (base name: "pickUpTime")', function() {
      // uncomment below and update the code to test the property pickUpTime
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property pointOfSale (base name: "pointOfSale")', function() {
      // uncomment below and update the code to test the property pointOfSale
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property readyForPickUp (base name: "readyForPickUp")', function() {
      // uncomment below and update the code to test the property readyForPickUp
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

    it('should have the property warehouse (base name: "warehouse")', function() {
      // uncomment below and update the code to test the property warehouse
      //var instane = new KoronacloudApiV3.CustomerOrder();
      //expect(instance).to.be();
    });

  });

}));
