/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3
 * Contact: support@combase.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KoronacloudApiV3);
  }
}(this, function(expect, KoronacloudApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KoronacloudApiV3.Customer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Customer', function() {
    it('should create an instance of Customer', function() {
      // uncomment below and update the code to test Customer
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be.a(KoronacloudApiV3.Customer);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property revision (base name: "revision")', function() {
      // uncomment below and update the code to test the property revision
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property birthday (base name: "birthday")', function() {
      // uncomment below and update the code to test the property birthday
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property cards (base name: "cards")', function() {
      // uncomment below and update the code to test the property cards
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property customerGroup (base name: "customerGroup")', function() {
      // uncomment below and update the code to test the property customerGroup
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property economicZone (base name: "economicZone")', function() {
      // uncomment below and update the code to test the property economicZone
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property informations (base name: "informations")', function() {
      // uncomment below and update the code to test the property informations
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property taxId (base name: "taxId")', function() {
      // uncomment below and update the code to test the property taxId
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property privacyPolicyAccepted (base name: "privacyPolicyAccepted")', function() {
      // uncomment below and update the code to test the property privacyPolicyAccepted
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

    it('should have the property marketingContactPermitted (base name: "marketingContactPermitted")', function() {
      // uncomment below and update the code to test the property marketingContactPermitted
      //var instane = new KoronacloudApiV3.Customer();
      //expect(instance).to.be();
    });

  });

}));
