/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KoronacloudApiV3);
  }
}(this, function(expect, KoronacloudApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KoronacloudApiV3.DayRating();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DayRating', function() {
    it('should create an instance of DayRating', function() {
      // uncomment below and update the code to test DayRating
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be.a(KoronacloudApiV3.DayRating);
    });

    it('should have the property cashier (base name: "cashier")', function() {
      // uncomment below and update the code to test the property cashier
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property organizationalUnit (base name: "organizationalUnit")', function() {
      // uncomment below and update the code to test the property organizationalUnit
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property receipts (base name: "receipts")', function() {
      // uncomment below and update the code to test the property receipts
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property revenue (base name: "revenue")', function() {
      // uncomment below and update the code to test the property revenue
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property visitors (base name: "visitors")', function() {
      // uncomment below and update the code to test the property visitors
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

    it('should have the property weather (base name: "weather")', function() {
      // uncomment below and update the code to test the property weather
      //var instane = new KoronacloudApiV3.DayRating();
      //expect(instance).to.be();
    });

  });

}));
