/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3
 * Contact: support@combase.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KoronacloudApiV3);
  }
}(this, function(expect, KoronacloudApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KoronacloudApiV3.StockReceipt();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StockReceipt', function() {
    it('should create an instance of StockReceipt', function() {
      // uncomment below and update the code to test StockReceipt
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be.a(KoronacloudApiV3.StockReceipt);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property revision (base name: "revision")', function() {
      // uncomment below and update the code to test the property revision
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property arrivalDate (base name: "arrivalDate")', function() {
      // uncomment below and update the code to test the property arrivalDate
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property bookingTime (base name: "bookingTime")', function() {
      // uncomment below and update the code to test the property bookingTime
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property bookingUser (base name: "bookingUser")', function() {
      // uncomment below and update the code to test the property bookingUser
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property cashier (base name: "cashier")', function() {
      // uncomment below and update the code to test the property cashier
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property createUser (base name: "createUser")', function() {
      // uncomment below and update the code to test the property createUser
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property dispatchNotification (base name: "dispatchNotification")', function() {
      // uncomment below and update the code to test the property dispatchNotification
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property itemsCount (base name: "itemsCount")', function() {
      // uncomment below and update the code to test the property itemsCount
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property organizationalUnit (base name: "organizationalUnit")', function() {
      // uncomment below and update the code to test the property organizationalUnit
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property partyInformation (base name: "partyInformation")', function() {
      // uncomment below and update the code to test the property partyInformation
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property pointOfSale (base name: "pointOfSale")', function() {
      // uncomment below and update the code to test the property pointOfSale
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property productStockOrder (base name: "productStockOrder")', function() {
      // uncomment below and update the code to test the property productStockOrder
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property sourceOrganizationalUnit (base name: "sourceOrganizationalUnit")', function() {
      // uncomment below and update the code to test the property sourceOrganizationalUnit
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property supplier (base name: "supplier")', function() {
      // uncomment below and update the code to test the property supplier
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new KoronacloudApiV3.StockReceipt();
      //expect(instance).to.be();
    });

  });

}));
