/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KoronacloudApiV3);
  }
}(this, function(expect, KoronacloudApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KoronacloudApiV3.CommodityGroupsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CommodityGroupsApi', function() {
    describe('addCommodityGroups', function() {
      it('should call addCommodityGroups successfully', function(done) {
        //uncomment below and update the code to test addCommodityGroups
        //instance.addCommodityGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCommodityGroup', function() {
      it('should call deleteCommodityGroup successfully', function(done) {
        //uncomment below and update the code to test deleteCommodityGroup
        //instance.deleteCommodityGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCommodityGroup', function() {
      it('should call getCommodityGroup successfully', function(done) {
        //uncomment below and update the code to test getCommodityGroup
        //instance.getCommodityGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCommodityGroups', function() {
      it('should call getCommodityGroups successfully', function(done) {
        //uncomment below and update the code to test getCommodityGroups
        //instance.getCommodityGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCommodityGroup', function() {
      it('should call updateCommodityGroup successfully', function(done) {
        //uncomment below and update the code to test updateCommodityGroup
        //instance.updateCommodityGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCommodityGroups', function() {
      it('should call updateCommodityGroups successfully', function(done) {
        //uncomment below and update the code to test updateCommodityGroups
        //instance.updateCommodityGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
