/**
 * KORONA.cloud API v3
 * Our api provides access to our cloud services
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KoronacloudApiV3);
  }
}(this, function(expect, KoronacloudApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KoronacloudApiV3.CustomerOrdersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomerOrdersApi', function() {
    describe('addCustomerOrders', function() {
      it('should call addCustomerOrders successfully', function(done) {
        //uncomment below and update the code to test addCustomerOrders
        //instance.addCustomerOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCustomerOrder', function() {
      it('should call deleteCustomerOrder successfully', function(done) {
        //uncomment below and update the code to test deleteCustomerOrder
        //instance.deleteCustomerOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerOrder', function() {
      it('should call getCustomerOrder successfully', function(done) {
        //uncomment below and update the code to test getCustomerOrder
        //instance.getCustomerOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerOrders', function() {
      it('should call getCustomerOrders successfully', function(done) {
        //uncomment below and update the code to test getCustomerOrders
        //instance.getCustomerOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerOrder', function() {
      it('should call updateCustomerOrder successfully', function(done) {
        //uncomment below and update the code to test updateCustomerOrder
        //instance.updateCustomerOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerOrders', function() {
      it('should call updateCustomerOrders successfully', function(done) {
        //uncomment below and update the code to test updateCustomerOrders
        //instance.updateCustomerOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
